"""Add_product_details

Revision ID: 01a43f851068
Revises: 8dd0e987d89d
Create Date: 2026-01-09 23:29:30.451177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a43f851068'
down_revision: Union[str, None] = '8dd0e987d89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(), nullable=True))
    op.add_column('product', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('product', sa.Column('farmer_name', sa.String(), nullable=True))
    op.add_column('product', sa.Column('harvest_date', sa.String(), nullable=True))
    op.add_column('product', sa.Column('moisture_content', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('vanillin_content', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'vanillin_content')
    op.drop_column('product', 'moisture_content')
    op.drop_column('product', 'harvest_date')
    op.drop_column('product', 'farmer_name')
    op.drop_column('product', 'origin')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
