"""Add missing User columns

Revision ID: 6ba196d2c05f
Revises: f8a3c2e91b45
Create Date: 2026-01-28 22:55:40.817018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba196d2c05f'
down_revision: Union[str, None] = 'f8a3c2e91b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sourcing_offers', 'producer_profiles', ['facilitator_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyb_status', sa.String(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'kyb_status')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'sourcing_offers', type_='foreignkey')
    # ### end Alembic commands ###
