"""Add product grade

Revision ID: a1b3eb4d1133
Revises: 6ba196d2c05f
Create Date: 2026-01-28 23:29:07.453533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b3eb4d1133'
down_revision: Union[str, None] = '6ba196d2c05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'grade')
    # ### end Alembic commands ###
