"""Add sourcing advanced fields

Revision ID: d2a6e1944df1
Revises: d379f3c754b7
Create Date: 2026-01-10 13:36:26.572737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a6e1944df1'
down_revision: Union[str, None] = 'd379f3c754b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sourcing_offers', sa.Column('cert_proofs_urls', sa.JSON(), nullable=True))
    op.add_column('sourcing_offers', sa.Column('trust_score_snapshot', sa.Float(), nullable=True))
    op.add_column('sourcing_requests', sa.Column('required_certs', sa.JSON(), nullable=True))
    op.add_column('sourcing_requests', sa.Column('logistics_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourcing_requests', 'logistics_status')
    op.drop_column('sourcing_requests', 'required_certs')
    op.drop_column('sourcing_offers', 'trust_score_snapshot')
    op.drop_column('sourcing_offers', 'cert_proofs_urls')
    # ### end Alembic commands ###
