"""Add sourcing module

Revision ID: d379f3c754b7
Revises: 01a43f851068
Create Date: 2026-01-10 13:27:10.801685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd379f3c754b7'
down_revision: Union[str, None] = '01a43f851068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('volume_target_kg', sa.Float(), nullable=True),
    sa.Column('price_target_usd', sa.Float(), nullable=True),
    sa.Column('grade_target', sa.String(), nullable=True),
    sa.Column('accepts_partial', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('specs_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sourcing_requests_buyer_id'), 'sourcing_requests', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sourcing_requests_id'), 'sourcing_requests', ['id'], unique=False)
    op.create_index(op.f('ix_sourcing_requests_product_type'), 'sourcing_requests', ['product_type'], unique=False)
    op.create_table('sourcing_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('facilitator_id', sa.Integer(), nullable=True),
    sa.Column('volume_offered_kg', sa.Float(), nullable=True),
    sa.Column('price_offered_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['sourcing_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sourcing_offers_facilitator_id'), 'sourcing_offers', ['facilitator_id'], unique=False)
    op.create_index(op.f('ix_sourcing_offers_id'), 'sourcing_offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sourcing_offers_id'), table_name='sourcing_offers')
    op.drop_index(op.f('ix_sourcing_offers_facilitator_id'), table_name='sourcing_offers')
    op.drop_table('sourcing_offers')
    op.drop_index(op.f('ix_sourcing_requests_product_type'), table_name='sourcing_requests')
    op.drop_index(op.f('ix_sourcing_requests_id'), table_name='sourcing_requests')
    op.drop_index(op.f('ix_sourcing_requests_buyer_id'), table_name='sourcing_requests')
    op.drop_table('sourcing_requests')
    # ### end Alembic commands ###
